'use strict'

module.exports = [
  'organisation_code',
  'name',
  'national_grouping',
  'high_level_health_geography',
  'address_line_1',
  'address_line_2',
  'address_line_3',
  'address_line_4',
  'address_line_5',
  'postcode',
  'open_date',
  'close_date',
  null,
  null,
  'local_authority',
  null,
  null,
  'contact_telephone_number',
  null,
  null,
  null,
  'amended_record_indicator',
  null,
  'current_care_organisation',
  'type_of_establishment',
  null,
  null
]
