'use strict'

module.exports = [
  'Organisation Code',
  'Name',
  'National Grouping',
  'High Level Health Geography',
  'Address Line 1',
  'Address Line 2',
  'Address Line 3',
  'Address Line 4',
  'Address Line 5',
  'Postcode',
  'Open Date',
  'Close Date',
  null,
  null,
  'Local Authority',
  null,
  null,
  'Contact Telephone Number',
  null,
  null,
  null,
  'Amended Record Indicator',
  null,
  'Current Care Organisation',
  'Type of Establishment',
  null,
  null,
]
